//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMaiTouchEmulator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfMaiTouchEmulator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic port connecting.
        /// </summary>
        internal static string lbAutoPortConnecting {
            get {
                return ResourceManager.GetString("lbAutoPortConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic sensor window positioning.
        /// </summary>
        internal static string lbAutoSensorPositioning {
            get {
                return ResourceManager.GetString("lbAutoSensorPositioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button State.
        /// </summary>
        internal static string lbButtonState {
            get {
                return ResourceManager.GetString("lbButtonState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection state.
        /// </summary>
        internal static string lbConnectionState {
            get {
                return ResourceManager.GetString("lbConnectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string lbConnectionStateNotConnected {
            get {
                return ResourceManager.GetString("lbConnectionStateNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to port.
        /// </summary>
        internal static string lbConnectToPort {
            get {
                return ResourceManager.GetString("lbConnectToPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        internal static string lbDebugMode {
            get {
                return ResourceManager.GetString("lbDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit when Sinmai exits.
        /// </summary>
        internal static string lbExitWithSinmai {
            get {
                return ResourceManager.GetString("lbExitWithSinmai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install com port.
        /// </summary>
        internal static string lbInstallComPort {
            get {
                return ResourceManager.GetString("lbInstallComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lbLanguageDropdown {
            get {
                return ResourceManager.GetString("lbLanguageDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed com ports.
        /// </summary>
        internal static string lbListComPorts {
            get {
                return ResourceManager.GetString("lbListComPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recieved.
        /// </summary>
        internal static string lbRecievedData {
            get {
                return ResourceManager.GetString("lbRecievedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string lbSentData {
            get {
                return ResourceManager.GetString("lbSentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall com port.
        /// </summary>
        internal static string lbUninstallComPort {
            get {
                return ResourceManager.GetString("lbUninstallComPort", resourceCulture);
            }
        }
    }
}
