//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfMaiTouchEmulator.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WpfMaiTouchEmulator.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string LbAbout {
            get {
                return ResourceManager.GetString("LbAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic port connecting.
        /// </summary>
        internal static string lbAutoPortConnecting {
            get {
                return ResourceManager.GetString("lbAutoPortConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try to automatically connect to COM23 to send touch sensor updates on app start.
        /// </summary>
        internal static string lbAutoPortConnectingTT {
            get {
                return ResourceManager.GetString("lbAutoPortConnectingTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic sensor window positioning.
        /// </summary>
        internal static string lbAutoSensorPositioning {
            get {
                return ResourceManager.GetString("lbAutoSensorPositioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try and automatically move the touch sensor window into the correct position on top of Sinmai.exe.
        /// </summary>
        internal static string lbAutoSensorPositioningTT {
            get {
                return ResourceManager.GetString("lbAutoSensorPositioningTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        internal static string LbBorderDisabled {
            get {
                return ResourceManager.GetString("LbBorderDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rainbow.
        /// </summary>
        internal static string LbBorderRainbow {
            get {
                return ResourceManager.GetString("LbBorderRainbow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border Settings.
        /// </summary>
        internal static string LbBorderSettings {
            get {
                return ResourceManager.GetString("LbBorderSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solid.
        /// </summary>
        internal static string LbBorderSolid {
            get {
                return ResourceManager.GetString("LbBorderSolid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Button State.
        /// </summary>
        internal static string lbButtonState {
            get {
                return ResourceManager.GetString("lbButtonState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COM Port.
        /// </summary>
        internal static string LbComPort {
            get {
                return ResourceManager.GetString("LbComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection state.
        /// </summary>
        internal static string lbConnectionState {
            get {
                return ResourceManager.GetString("lbConnectionState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected.
        /// </summary>
        internal static string lbConnectionStateNotConnected {
            get {
                return ResourceManager.GetString("lbConnectionStateNotConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect to port.
        /// </summary>
        internal static string lbConnectToPort {
            get {
                return ResourceManager.GetString("lbConnectToPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug mode.
        /// </summary>
        internal static string lbDebugMode {
            get {
                return ResourceManager.GetString("lbDebugMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show the touchpad with translucency and show inputs highlighted.
        /// </summary>
        internal static string lbDebugModeTT {
            get {
                return ResourceManager.GetString("lbDebugModeTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emulate ring buttons.
        /// </summary>
        internal static string lbEmulateRingButtons {
            get {
                return ResourceManager.GetString("lbEmulateRingButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Useful when navigating the menus without a keyboard.
        /// </summary>
        internal static string lbEmulateRingButtonsTT {
            get {
                return ResourceManager.GetString("lbEmulateRingButtonsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit when Sinmai exits.
        /// </summary>
        internal static string lbExitWithSinmai {
            get {
                return ResourceManager.GetString("lbExitWithSinmai", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try and detect when Sinmai.exe exits and exit this app alongside it.
        /// </summary>
        internal static string lbExitWithSinmaiTT {
            get {
                return ResourceManager.GetString("lbExitWithSinmaiTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install com port.
        /// </summary>
        internal static string lbInstallComPort {
            get {
                return ResourceManager.GetString("lbInstallComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string lbLanguageDropdown {
            get {
                return ResourceManager.GetString("lbLanguageDropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend ring button size.
        /// </summary>
        internal static string lbLargeButtons {
            get {
                return ResourceManager.GetString("lbLargeButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extends the ring button hitboxes to the edge of the window.
        /// </summary>
        internal static string lbLargeButtonsTT {
            get {
                return ResourceManager.GetString("lbLargeButtonsTT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List installed com ports.
        /// </summary>
        internal static string lbListComPorts {
            get {
                return ResourceManager.GetString("lbListComPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Help.
        /// </summary>
        internal static string lbMenuCategoryHelp {
            get {
                return ResourceManager.GetString("lbMenuCategoryHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show setup instructions.
        /// </summary>
        internal static string lbMenuItemSetup {
            get {
                return ResourceManager.GetString("lbMenuItemSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open log folder.
        /// </summary>
        internal static string LbOpenLogFolder {
            get {
                return ResourceManager.GetString("LbOpenLogFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        internal static string lbRecievedData {
            get {
                return ResourceManager.GetString("lbRecievedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent.
        /// </summary>
        internal static string lbSentData {
            get {
                return ResourceManager.GetString("lbSentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string LbSettings {
            get {
                return ResourceManager.GetString("LbSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag.
        /// </summary>
        internal static string LbTouchPanelDrag {
            get {
                return ResourceManager.GetString("LbTouchPanelDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize.
        /// </summary>
        internal static string LbTouchPanelResize {
            get {
                return ResourceManager.GetString("LbTouchPanelResize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall com port.
        /// </summary>
        internal static string lbUninstallComPort {
            get {
                return ResourceManager.GetString("lbUninstallComPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port COM3 already registered. Either remove it via Device Manager or uninstall the virtual port..
        /// </summary>
        internal static string TxtCom3AlreadyInstalled {
            get {
                return ResourceManager.GetString("TxtCom3AlreadyInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port COM3 successfully installed..
        /// </summary>
        internal static string TxtCom3InstalledSuccessfully {
            get {
                return ResourceManager.GetString("TxtCom3InstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port COM3 failed to install.
        /// </summary>
        internal static string TxtCom3InstallFailed {
            get {
                return ResourceManager.GetString("TxtCom3InstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port COM3 successfully uninstalled..
        /// </summary>
        internal static string TxtCom3UninstalledSuccessfully {
            get {
                return ResourceManager.GetString("TxtCom3UninstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port COM3 failed to uninstall. It may be a real device, uninstall it from Device Manager.
        /// </summary>
        internal static string TxtCom3UninstallFailed {
            get {
                return ResourceManager.GetString("TxtCom3UninstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port COM3 not found. No need to uninstall..
        /// </summary>
        internal static string TxtCom3UninstallNotRequired {
            get {
                return ResourceManager.GetString("TxtCom3UninstallNotRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to port.
        /// </summary>
        internal static string TxtComPortConnected {
            get {
                return ResourceManager.GetString("TxtComPortConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conecting....
        /// </summary>
        internal static string TxtComPortConnecting {
            get {
                return ResourceManager.GetString("TxtComPortConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed ports.
        /// </summary>
        internal static string TxtCurrentlyInstalledPorts {
            get {
                return ResourceManager.GetString("TxtCurrentlyInstalledPorts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error connecting to COM port.
        /// </summary>
        internal static string TxtErrorConnectingToPortHeader {
            get {
                return ResourceManager.GetString("TxtErrorConnectingToPortHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to listen for Sinmai exit signal, this can happen when Sinmai.exe is being run as admin.\n\nAutomatic exiting disabled..
        /// </summary>
        internal static string TxtFailedToSetupSinmaiExit {
            get {
                return ResourceManager.GetString("TxtFailedToSetupSinmaiExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to listen for Sinmai exit.
        /// </summary>
        internal static string TxtFailedToSetupSinmaiExitHeader {
            get {
                return ResourceManager.GetString("TxtFailedToSetupSinmaiExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please remove any COM devices using the COM3 port before installing the virtual COM port. In Device Manager click &quot;View&quot; then enabled &quot;Show hidden devices&quot; and uninstall any devices that are using the COM3 port.
        ///
        ///After ensuring COM3 is free please use the install COM port button in the app to register the app.
        ///
        ///The app needs to connect to the port prior to Sinmai.exe being opened..
        /// </summary>
        internal static string TxtSetupInstructions {
            get {
                return ResourceManager.GetString("TxtSetupInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First time setup.
        /// </summary>
        internal static string TxtSetupInstructionsHeader {
            get {
                return ResourceManager.GetString("TxtSetupInstructionsHeader", resourceCulture);
            }
        }
    }
}
